Fix broken permission check in cut action
contao/news-bundle pull request #38
Opened 2018-06-28 10:34 UTC by dmolineus

When enabling custom sorting for news (customer uses example explained here http://help.rocksolidthemes.com/discussions/contao/16551-verwendung-reihenfolge-der-portfolio-eintrge#comment_40419059) the permission check fails for regular users if they try to move a new item.

This is caused because the pid refers to the news id of the related news item when moving. This PR fixes the issue.

2018-06-28 11:01 UTC, fritzmg commented
Does it only occur for `cut`? See also https://github.com/contao/core/issues/8887

2018-07-02 14:41 UTC, leofeyer commented
I think we should keep the two `case` statements together and do `if (Input::get('act') == 'cut' && Input::get('mode') == 1)`. Then we don't need to duplicate all the code from the following case.

2018-07-02 14:42 UTC, leofeyer requested changes
I think we should keep the two `case` statements together and do `if (Input::get('act') == 'cut' && Input::get('mode') == 1)`. Then we don't need to duplicate all the code from the following case.

2018-07-03 06:23 UTC, dmolineus commented
@leofeyer You're right. Didn't notice the missing break after the `cut` and `copy` section the first time. I reworked the fix.

2018-07-17 07:53 UTC, merged

2018-07-17 07:53 UTC, leofeyer commented
Thank you @dmolineus.